stages:

  extraction:
    cmd: python src/extraction.py
    deps:
      - src/extraction.py
    outs:
      - data/raw/data.csv

  cleaning:
    cmd: python src/cleaning.py
    deps:
      - src/cleaning.py
      - data/raw/data.csv
    outs:
      - data/processed/clean_data

  transformation:
    cmd: python src/transformation.py
    deps:
      - src/transformation.py
      - data/processed/clean_data
    outs:
      - data/transformed/train
      - data/transformed/test
      - models/pipeline

  load:
    cmd: python src/load.py
    deps:
      - src/load.py
      - data/transformed/train
      - data/transformed/test

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/transformed/train
      - data/transformed/test
    outs:
      - mlflow.db

  best_model:
    cmd: python src/best_model.py
    deps:
      - src/best_model.py
      - mlflow.db